#!/usr/bin/env python3
"""
Collect public course-market signals for Taiwan executive leadership programs.

The script intentionally keeps raw observations separate from the final curated
database. Raw observations can include duplicates and weak matches; the final
site should use the reviewed JSON generated by a later step.
"""

from __future__ import annotations

import datetime as dt
import hashlib
import html
import json
import re
import time
from pathlib import Path
from typing import Any
from urllib.parse import quote, urljoin
from urllib.request import Request, urlopen


BASE_DIR = Path(__file__).resolve().parent
OUT_DIR = BASE_DIR
USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126 Safari/537.36"
)

ACCUPASS_QUERIES = [
    "高階主管",
    "高階經理人",
    "企業主 課程",
    "CEO 課程",
    "經營管理 課程",
    "領導力",
    "領導力發展",
    "主管領導",
    "團隊領導",
    "教練式領導",
    "變革領導",
    "情境領導",
    "跨世代領導",
    "當責領導",
    "韌性領導",
    "AI 領導力",
    "AI 管理 主管",
    "AI 決策",
    "AI 轉型",
    "數位轉型 管理",
    "組織變革",
    "組織發展",
    "人才發展 主管",
    "接班 企業二代",
    "企業二代",
    "EMBA 高階經理人",
    "EMBA 招生",
    "商業敏銳度",
    "問題解決 管理",
    "策略思考",
    "策略管理",
    "績效管理",
    "OKR 主管",
    "高績效團隊",
    "目標管理",
    "授權 主管",
    "溝通 主管",
    "向上管理",
    "影響力 領導",
    "談判 領導",
    "商業談判",
    "衝突管理",
    "心理安全感",
    "組織文化",
    "學習型組織",
    "ESG 領導",
    "永續 經營 管理",
    "董事會 課程",
    "企業治理 課程",
    "財務管理 主管",
    "商業模式 課程",
    "第二曲線",
    "創新管理",
    "專案管理 主管",
    "敏捷管理",
    "店長 管理",
    "零售主管",
    "業務主管",
    "銷售領導",
    "人資主管",
    "教練 課程 主管",
    "ICF 主管",
    "AMA 領導力",
    "DDI 領導力",
    "卡內基 主管",
    "天下 領導 主管",
]

TARGET_URLS = [
    "https://bwlearning.businessweekly.com.tw/",
    "https://bwlearning.businessweekly.com.tw/billionceo",
    "https://bwlearning.businessweekly.com.tw/ceo50",
    "https://bwlearning.businessweekly.com.tw/dt",
    "https://bwlearning.businessweekly.com.tw/evp",
    "https://bwlearning.businessweekly.com.tw/management",
    "https://bwlearning.businessweekly.com.tw/expression",
    "https://bwlearning.businessweekly.com.tw/training",
    "https://bwlearning.businessweekly.com.tw/impact",
    "https://bwlearning.businessweekly.com.tw/ceoclub",
    "https://leaderimpact.cwgv.com.tw/",
    "https://leaderimpact.cwgv.com.tw/course/latest",
    "https://leaderimpact.cwgv.com.tw/course/1626",
    "https://leaderimpact.cwgv.com.tw/course/1629",
    "https://leaderimpact.cwgv.com.tw/course/1630",
    "https://leaderimpact.cwgv.com.tw/course/1595",
    "https://leaderimpact.cwgv.com.tw/course/1576",
    "https://leaderimpact.cwgv.com.tw/course/1634",
    "https://edm.managertoday.com.tw/lead/",
    "https://edm.managertoday.com.tw/performance_driven_method/",
    "https://edm.managertoday.com.tw/performance_team/",
    "https://edm.managertoday.com.tw/performance_pf/",
    "https://edm.managertoday.com.tw/nextleader/",
    "https://edm.managertoday.com.tw/super/",
    "https://edm.managertoday.com.tw/future-manager/",
    "https://edm.managertoday.com.tw/logic_of_ai/",
    "https://edm.managertoday.com.tw/AI_smartwork/",
    "https://edm.managertoday.com.tw/negotiation-program/",
    "https://edm.managertoday.com.tw/negotiation/2026q4/",
    "https://edm.managertoday.com.tw/the_managers_toolkit/",
    "https://edm.managertoday.com.tw/2026_taitra_aiadvanced_web/",
    "https://www.harment.com/open-course/high-class",
    "https://www.harment.com/blank/20260429-sl2-leadership",
    "https://www.harment.com/blank/20260729-sl2-leadership",
    "https://www.harment.com/blank/20260811-leadership-challenge",
    "https://www.harment.com/blank/20260909-lead-people-to-change",
    "https://www.harment.com/blank/20260902-self-leadership",
    "https://www.harment.com/blank/20260707-management-sysrem-for-managers",
    "https://www.harment.com/blank/20261028-management-sysrem-for-managers1",
    "https://www.harment.com/blank/20261020-coaching-essentials",
    "https://www.harment.com/blank/20261006-leadership-builder",
    "https://www.harment.com/blank/20260610-essential-skills-of-communicating-up",
    "https://www.harment.com/blank/20260813-improving-work-habits-coaching-job-skills",
    "https://www.carnegie.com.tw/course-list/course-for-personal-development-mj",
    "https://www.carnegie.com.tw/course-list/course-for-personal-development-mj/course-schedule",
    "https://www.carnegie.com.tw/course-list/course-for-personal-development-ltm/course-schedule",
    "https://www.carnegie.com.tw/event-list/seminar-ai-leadership-mindset",
    "https://www.ddiworld.com.tw/search?keys=%E9%A0%98%E5%B0%8E%E5%8A%9B",
    "https://www.ddiworld.com.tw/resource/news/ddi_bwlearning_evp_2025",
    "https://www.cpma.org.tw/news/main_detail.php?id=78",
    "https://emba.nccu.edu.tw/",
    "https://emba.ntu.edu.tw/",
    "https://emba.ncku.edu.tw/",
    "https://emba.ncku.edu.tw/p/404-1140-297492.php?Lang=zh-tw",
    "https://emba.ncku.edu.tw/p/406-1140-291603%2Cr11.php?Lang=zh-tw",
    "https://www.emba.nchu.edu.tw/",
    "https://emba.thu.edu.tw/",
]

RELEVANCE_KEYWORDS = [
    "高階",
    "主管",
    "經理人",
    "CEO",
    "企業主",
    "領導",
    "管理",
    "經營",
    "策略",
    "變革",
    "轉型",
    "績效",
    "團隊",
    "教練",
    "賦能",
    "決策",
    "接班",
    "EMBA",
    "人才",
    "組織",
    "AI",
    "永續",
    "治理",
    "談判",
]


def fetch(url: str, timeout: int = 20) -> str:
    req = Request(url, headers={"User-Agent": USER_AGENT})
    with urlopen(req, timeout=timeout) as res:
        raw = res.read()
    return raw.decode("utf-8", "ignore")


def clean_text(raw_html: str) -> str:
    raw_html = re.sub(r"<script.*?</script>|<style.*?</style>", " ", raw_html, flags=re.S | re.I)
    text = html.unescape(re.sub(r"<[^>]+>", " ", raw_html))
    return re.sub(r"\s+", " ", text).strip()


def strip_tags(fragment: str) -> str:
    return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", " ", fragment))).strip()


def extract_title(raw_html: str, fallback: str = "") -> str:
    m = re.search(r"<title>(.*?)</title>", raw_html, flags=re.S | re.I)
    if m:
        return strip_tags(m.group(1)).replace("｜ACCUPASS", "").strip()
    return fallback


def relevance_score(text: str) -> int:
    up = text.upper()
    score = 0
    for kw in RELEVANCE_KEYWORDS:
        if kw.upper() in up:
            score += 2 if kw in ["高階", "CEO", "企業主", "EMBA", "領導", "經理人"] else 1
    weak_exclusions = [
        "親子",
        "瑜珈",
        "手作",
        "音樂",
        "寵物",
        "投資講座",
        "心理諮商",
        "日語",
        "中醫",
        "戀愛",
        "薩提爾",
        "桌遊",
        "基層主管",
        "秘書",
    ]
    for kw in weak_exclusions:
        if kw in text:
            score -= 3
    return score


def parse_accupass_search(query: str, raw_html: str) -> list[dict[str, Any]]:
    observations: list[dict[str, Any]] = []
    chunks = raw_html.split("EventCard_home-event-card")
    for chunk in chunks[1:]:
        event_match = re.search(r'href="/event/([0-9]+)[^"]*"', chunk)
        title_match = re.search(r'EventCard_event-name[^>]*>(.*?)</p>', chunk, flags=re.S)
        time_match = re.search(r'EventCard_event-time[^>]*>(.*?)</p>', chunk, flags=re.S)
        loc_match = re.search(r"EventPlaceType[^>]*>.*?<span>(.*?)</span>", chunk, flags=re.S)
        tag_match = re.search(r'TagStatsBottom_tag[^>]*>(.*?)</a>', chunk, flags=re.S)
        counts = re.findall(r'alt="(?:page-view|like-count)".{0,260}?<span>([0-9,]+)</span>', chunk, flags=re.S)
        if not event_match or not title_match:
            continue
        title = strip_tags(title_match.group(1).replace("<!-- -->", ""))
        event_id = event_match.group(1)
        views = int(counts[0].replace(",", "")) if len(counts) > 0 else None
        likes = int(counts[1].replace(",", "")) if len(counts) > 1 else None
        obs = {
            "type": "accupass_search_card",
            "query": query,
            "event_id": event_id,
            "source_url": f"https://www.accupass.com/event/{event_id}",
            "title": title,
            "time_text": strip_tags(time_match.group(1)) if time_match else "",
            "location": strip_tags(loc_match.group(1)) if loc_match else "",
            "tags": strip_tags(tag_match.group(1).replace("<!-- -->", "")) if tag_match else "",
            "views": views,
            "likes": likes,
        }
        obs["relevance_score"] = relevance_score(" ".join(str(v) for v in obs.values()))
        observations.append(obs)
    return observations


def extract_price(text: str) -> str:
    patterns = [
        r"(NT\.?\s?\$?\s?[0-9,]+(?:\s*[~起/／-]\s*[0-9,]+)?\s*(?:元|/人|／人)?)",
        r"(公開班課程價格\s*\$?[0-9,]+\s*元/人)",
        r"(課程費用[:：]?\s*[0-9,]+\s*元)",
        r"(費用\s*[0-9,]+\s*元)",
        r"(早鳥[^。]{0,20}[0-9,]+\s*元)",
        r"(一般票\s*NT\.?\s?[0-9,]+)",
    ]
    hits: list[str] = []
    for pat in patterns:
        for match in re.findall(pat, text, flags=re.I):
            val = re.sub(r"\s+", " ", match).strip()
            if val not in hits:
                hits.append(val)
    return "；".join(hits[:3]) if hits else "未公開/需洽詢"


def extract_teacher(text: str) -> str:
    patterns = [
        r"授課講師[:：]?\s*([A-Za-z\u4e00-\u9fff・．,\s&、／/]{2,60})",
        r"講師[:：]\s*([A-Za-z\u4e00-\u9fff・．,\s&、／/]{2,60})",
        r"由([A-Za-z\u4e00-\u9fff・．,\s&、／/]{2,40})(?:親授|主講|帶領)",
        r"([A-Za-z\u4e00-\u9fff]{2,4})\s*(?:老師|顧問|教授|社長|董事長|總經理|執行長)",
    ]
    candidates: list[str] = []
    for pat in patterns:
        for match in re.findall(pat, text):
            name = re.sub(r"\s+", " ", match).strip(" ，。:：、")
            if 2 <= len(name) <= 60 and name not in candidates:
                candidates.append(name)
    return "；".join(candidates[:4]) if candidates else "未公開/機構講師群"


def extract_organizer(text: str, raw_html: str, default: str = "") -> str:
    json_match = re.search(r'"organizer":\{[^{}]*"title":"([^"]+)"', raw_html)
    if json_match:
        return html.unescape(json_match.group(1))
    org_patterns = [
        r"主辦單位[:：]\s*([A-Za-z\u4e00-\u9fff（）()·．\s]+)",
        r"主辦[:：]\s*([A-Za-z\u4e00-\u9fff（）()·．\s]+)",
    ]
    for pat in org_patterns:
        m = re.search(pat, text)
        if m:
            return re.sub(r"\s+", " ", m.group(1)).strip()[:40]
    return default


def classify_category(title: str, text: str = "") -> str:
    body = f"{title} {text}"
    rules = [
        ("AI決策與AI領導", ["AI", "人工智慧", "生成式", "自動化", "智能"]),
        ("組織變革與轉型", ["變革", "轉型", "改變", "變局"]),
        ("策略與第二曲線", ["策略", "第二曲線", "成長藍圖", "商業模式", "造局"]),
        ("高階經營與CEO", ["CEO", "企業主", "董事長", "總經理", "高階經營", "百億"]),
        ("EMBA與學位學程", ["EMBA", "碩士", "學分班", "招生"]),
        ("團隊領導與高績效團隊", ["團隊", "高績效", "帶人", "主管養成"]),
        ("教練式領導與賦能", ["教練", "輔導", "賦能", "Coaching"]),
        ("溝通影響力與簡報", ["溝通", "影響力", "簡報", "表達", "說服"]),
        ("商業談判與協商", ["談判", "協商", "破局"]),
        ("績效管理與目標管理", ["績效", "OKR", "目標", "KPI"]),
        ("人才策略與接班", ["人才", "接班", "二代", "梯隊", "EVP"]),
        ("當責與執行力", ["當責", "執行力", "Accountability"]),
        ("跨世代領導", ["跨世代", "世代", "Z世代"]),
        ("韌性與心理安全", ["韌性", "復原力", "心理安全", "情緒"]),
        ("問題解決與決策", ["問題解決", "決策", "批判思考", "商業敏銳"]),
        ("財務與商業敏銳度", ["財務", "損益", "商業敏銳", "預算", "獲利"]),
        ("ESG永續與治理", ["ESG", "永續", "治理", "董事會"]),
        ("零售服務領導", ["店長", "門店", "零售", "服務"]),
        ("專案與敏捷管理", ["專案", "敏捷", "Scrum"]),
        ("銷售與業務領導", ["銷售", "業務", "客戶", "商務開發"]),
        ("國際視野與跨文化", ["國際", "全球", "跨文化", "海外"]),
        ("組織文化與學習型組織", ["組織文化", "學習型", "文化"]),
    ]
    for category, kws in rules:
        if any(kw.lower() in body.lower() for kw in kws):
            return category
    return "通用管理與領導力"


def make_course_from_observation(obs: dict[str, Any], detail: dict[str, Any] | None = None) -> dict[str, Any]:
    detail = detail or {}
    text = detail.get("text", "")
    title = detail.get("title") or obs.get("title", "")
    source_url = obs.get("source_url") or detail.get("source_url")
    org = detail.get("organizer") or obs.get("organizer") or ""
    views = obs.get("views")
    likes = obs.get("likes")
    hot_notes = []
    if views is not None:
        hot_notes.append(f"Accupass瀏覽 {views}")
    if likes is not None:
        hot_notes.append(f"收藏/喜歡 {likes}")
    for token in ["額滿", "完售", "熱賣", "加開", "好評", "席位有限"]:
        if token in f"{title} {text}":
            hot_notes.append(token)
    course_id = hashlib.md5(f"{source_url}|{title}".encode("utf-8")).hexdigest()[:10]
    return {
        "id": course_id,
        "title": title,
        "category": classify_category(title, text[:1200]),
        "provider": org or infer_provider_from_url(source_url),
        "source_url": source_url,
        "format": "線下/實體" if "Offline Event" in text or "線下" in text or "實體" in text else "需確認",
        "date": detail.get("date") or obs.get("time_text", "未公開"),
        "location": detail.get("location") or obs.get("location", "未公開"),
        "price": extract_price(text) if text else "未公開/需洽詢",
        "price_type": "公開標價" if text and extract_price(text) != "未公開/需洽詢" else "未公開/需洽詢",
        "teacher": extract_teacher(text) if text else "未公開/機構講師群",
        "teacher_background": summarize_teacher_background(text),
        "target_company": infer_target_company(title, text),
        "hotness": "；".join(hot_notes) if hot_notes else "未見公開量化熱度",
        "reputation": infer_reputation(title, text, views, likes),
        "evidence_level": detail.get("evidence_level", obs.get("type", "source_page")),
        "research_note": make_research_note(title, text),
    }


def infer_provider_from_url(url: str | None) -> str:
    if not url:
        return "未公開"
    mapping = {
        "accupass.com": "Accupass活動主辦單位",
        "managertoday": "經理人商學院",
        "bnextmedia": "經理人商學院",
        "bwlearning": "商周CEO學院",
        "leaderimpact": "領導影響力學院",
        "harment": "哈佛企管",
        "carnegie": "卡內基訓練",
        "ddiworld": "DDI美商宏智",
        "cpma": "中華民國企業經理協進會",
        "emba.nccu": "政大EMBA",
        "emba.ntu": "台大EMBA",
        "emba.ncku": "成大EMBA",
        "emba.nchu": "中興EMBA",
        "emba.thu": "東海EMBA",
    }
    for key, value in mapping.items():
        if key in url:
            return value
    return "未公開"


def summarize_teacher_background(text: str) -> str:
    if not text:
        return "未公開"
    cues = ["現任", "曾任", "前", "經驗", "顧問", "教授", "董事長", "總經理", "執行長", "創辦人"]
    sentences = re.split(r"[。！？\n]", text)
    picked: list[str] = []
    for sent in sentences:
        sent = re.sub(r"\s+", " ", sent).strip()
        if 20 <= len(sent) <= 160 and any(cue in sent for cue in cues):
            picked.append(sent)
        if len(picked) >= 2:
            break
    return "；".join(picked) if picked else "未公開/請見來源頁"


def infer_target_company(title: str, text: str) -> str:
    body = f"{title} {text}"
    if any(k in body for k in ["CEO", "企業主", "董事長", "總經理", "二代"]):
        return "企業主、總經理、二代接班、高階經營團隊"
    if any(k in body for k in ["AI", "轉型", "數位"]):
        return "推動AI/數位轉型的中大型企業、事業部主管、HR/L&D"
    if any(k in body for k in ["店長", "零售", "服務"]):
        return "連鎖零售、服務業、門市營運主管"
    if any(k in body for k in ["EMBA", "碩士", "學分班"]):
        return "具多年工作經驗的企業主、高階經理人、創業家"
    return "中高階主管、部門主管、專案/事業負責人"


def infer_reputation(title: str, text: str, views: int | None, likes: int | None) -> str:
    signals = []
    if views is not None and views >= 1000:
        signals.append("活動平台曝光高")
    elif views is not None and views >= 400:
        signals.append("活動平台有一定曝光")
    if likes is not None and likes >= 5:
        signals.append("收藏/喜歡數高於多數管理課")
    for token in ["好評", "滿意度", "完課", "力推", "額滿", "完售", "加開", "世界級", "財富500", "台積電"]:
        if token in f"{title} {text}":
            signals.append(token)
    return "；".join(dict.fromkeys(signals)) if signals else "未見公開口碑量化資料"


def make_research_note(title: str, text: str) -> str:
    body = f"{title} {text}"
    if "線上" in body and "實體" not in body and "線下" not in body:
        return "可能含線上內容，需二次確認實體比例。"
    if "需洽詢" in body or "索取" in body:
        return "價格或完整簡章可能需洽詢主辦單位。"
    return "以公開頁面可讀資訊整理。"


def parse_detail(source_url: str, fallback_title: str = "") -> dict[str, Any]:
    raw = fetch(source_url)
    text = clean_text(raw)
    title = extract_title(raw, fallback_title)
    organizer = extract_organizer(text, raw, infer_provider_from_url(source_url))
    date = ""
    date_match = re.search(r"20[2-3][0-9][./-][0-1]?[0-9][./-][0-3]?[0-9].{0,80}", text)
    if date_match:
        date = date_match.group(0).strip()
    if not date:
        json_start = re.search(r'"startDateTime":"([^"]+)"', raw)
        json_end = re.search(r'"endDateTime":"([^"]+)"', raw)
        if json_start:
            date = json_start.group(1) + (f" - {json_end.group(1)}" if json_end else "")
    location = ""
    loc_match = re.search(r"(?:地點|活動地點|課程地點)[:：]?\s*([^。]{4,80})", text)
    if loc_match:
        location = loc_match.group(1).strip()
    return {
        "source_url": source_url,
        "title": title,
        "organizer": organizer,
        "date": date,
        "location": location,
        "text": text[:24000],
        "evidence_level": "official_page",
    }


def collect() -> None:
    run_started = dt.datetime.now().isoformat(timespec="seconds")
    observations: list[dict[str, Any]] = []
    errors: list[dict[str, str]] = []

    for i, query in enumerate(ACCUPASS_QUERIES, 1):
        url = f"https://www.accupass.com/search?q={quote(query)}"
        try:
            raw = fetch(url)
            cards = parse_accupass_search(query, raw)
            observations.extend(cards)
            print(f"[{i:02d}/{len(ACCUPASS_QUERIES)}] {query}: {len(cards)} cards", flush=True)
        except Exception as exc:  # noqa: BLE001
            errors.append({"url": url, "error": repr(exc)})
            print(f"[ERR] {query}: {exc}", flush=True)
        time.sleep(0.12)

    (OUT_DIR / "raw_observations.json").write_text(
        json.dumps(observations, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    source_page_details: list[dict[str, Any]] = []
    discovered_urls = set(TARGET_URLS)

    # Add highly relevant Accupass event pages for detail enrichment.
    unique_events: dict[str, dict[str, Any]] = {}
    for obs in observations:
        event_id = obs.get("event_id")
        if not event_id:
            continue
        old = unique_events.get(event_id)
        if old is None or obs.get("relevance_score", 0) > old.get("relevance_score", 0):
            unique_events[event_id] = obs
    blocked_title_tokens = [
        "線上 online",
        "線上課程",
        "免費試讀",
        "心理諮商",
        "日語",
        "中醫",
        "薩提爾",
        "戀愛",
        "桌遊",
        "高階秘書",
        "基層主管",
    ]
    filtered_events = []
    for item in unique_events.values():
        title = item.get("title", "")
        tags = item.get("tags", "")
        if item.get("relevance_score", 0) < 5:
            continue
        if any(token in title for token in blocked_title_tokens):
            continue
        if "線上" in title and "實體" not in title and "線下" not in tags:
            continue
        filtered_events.append(item)

    relevant_events = sorted(
        filtered_events,
        key=lambda item: (
            item.get("relevance_score", 0),
            item.get("views") or 0,
            item.get("likes") or 0,
        ),
        reverse=True,
    )[:120]
    for obs in relevant_events:
        discovered_urls.add(obs["source_url"])

    for i, url in enumerate(sorted(discovered_urls), 1):
        try:
            detail = parse_detail(url)
            source_page_details.append(detail)
            print(f"[detail {i:03d}/{len(discovered_urls)}] {detail['title'][:50]}", flush=True)
        except Exception as exc:  # noqa: BLE001
            errors.append({"url": url, "error": repr(exc)})
            print(f"[ERR detail] {url}: {exc}", flush=True)
        time.sleep(0.08)

    # Create initial candidate courses from Accupass details and target pages.
    details_by_url = {item["source_url"]: item for item in source_page_details}
    candidate_courses: list[dict[str, Any]] = []
    seen_course_keys: set[str] = set()

    for obs in relevant_events:
        detail = details_by_url.get(obs["source_url"])
        course = make_course_from_observation(obs, detail)
        key = re.sub(r"\W+", "", course["title"].lower())[:80]
        if relevance_score(course["title"] + " " + course.get("research_note", "")) >= 4 and key not in seen_course_keys:
            seen_course_keys.add(key)
            candidate_courses.append(course)

    for detail in source_page_details:
        if "accupass.com/event/" in detail["source_url"]:
            continue
        title = detail["title"]
        course = make_course_from_observation(
            {
                "type": "target_source_page",
                "title": title,
                "source_url": detail["source_url"],
                "organizer": detail.get("organizer"),
            },
            detail,
        )
        key = re.sub(r"\W+", "", course["title"].lower())[:80]
        if relevance_score(title + " " + detail.get("text", "")[:1000]) >= 4 and key not in seen_course_keys:
            seen_course_keys.add(key)
            candidate_courses.append(course)

    summary = {
        "run_started": run_started,
        "run_finished": dt.datetime.now().isoformat(timespec="seconds"),
        "accupass_queries": len(ACCUPASS_QUERIES),
        "raw_search_observations": len(observations),
        "unique_accupass_events": len(unique_events),
        "detail_pages_attempted": len(discovered_urls),
        "detail_pages_collected": len(source_page_details),
        "candidate_courses": len(candidate_courses),
        "errors": errors,
    }

    (OUT_DIR / "source_page_details.json").write_text(
        json.dumps(source_page_details, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    (OUT_DIR / "candidate_courses_auto.json").write_text(
        json.dumps(candidate_courses, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    (OUT_DIR / "collection_summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    collect()
